# Generated by Django 2.0 on 2018-09-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_remove_message_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='userId',
            field=models.TextField(blank=True),
        ),
    ]
