# Generated by Django 2.0 on 2018-09-11 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_onemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneroom',
            name='users',
            field=models.ManyToManyField(related_name='checking', to=settings.AUTH_USER_MODEL),
        ),
    ]
